spring:
  application:
    name: session

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:nvidiaconvince}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:Grandy-092358}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000 # 30 phút để tránh đóng kết nối quá nhanh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
