spring:
 datasource:
    url: jdbc:mysql://localhost:3306/nvidiaconvince
    username: root
    password: Grandy-092358
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
 jpa:
    hibernate:
      ddl-auto: update 
